string1="thisismypython3programming"
print(string1.isalnum())
string2="thisistheprogram"
print(string2.isalpha())
print(string2.islower())
print(string2.isupper())
print(string2.isprintable())
print(string2.isspace())
print(string2.istitle())
string3="44"
print(string3.isdigit())
print(string3.isdecimal())